### ISSUE TITLE
distro is not indexed on CPAN

### ISSUE THREAD

**Issue by shawnlaffan** [jlapeyre/PDL-Fit-Levmar#3]
The PDL::Fit::Levmar package is not indexed by CPAN (see extract of index below), with the end result that it cannot be installed via the cpan or cpanm utilities.  

It also cannot be located by a search on metacpan.org, which returns an Error 404.  Fortunately that page has a link to some possible reasons why it might not be indexed: https://metacpan.org/about/missing_modules , and in this case it is probably because the distro needs a package file, even if skeletal, e.g. ```lib/PDL/Fit/Levmar.pm``` could contain just package and version statements.

I'm happy to work up a pull request if you want one.

Regards,
Shawn.

Extract from https://cpan.metacpan.org/modules/02packages.details.txt :
```
PDL::Finance::TA                  0.008  K/KM/KMX/PDL-Finance-TA-0.008.tar.gz
PDL::Finance::Talib               0.009  K/KM/KMX/PDL-Finance-Talib-0.009.tar.gz
PDL::Fit::Gaussian                undef  C/CH/CHM/PDL-2.018.tar.gz
PDL::Fit::Linfit                  undef  C/CH/CHM/PDL-2.018.tar.gz
PDL::Fit::LM                      undef  C/CH/CHM/PDL-2.018.tar.gz
PDL::Fit::Polynomial              undef  C/CH/CHM/PDL-2.018.tar.gz
PDL::Func                         undef  C/CH/CHM/PDL-2.018.tar.gz
PDL::FuncND                        0.11  D/DJ/DJERIUS/PDL-FuncND-0.11.tar.gz
```

**Comment by jlapeyre** [comment]
Hi Shawn,
Thanks for noting this. Yes, a  PR would be great.
John

**Comment by jlapeyre** [comment]
The package is now indexed on CPAN
