### ISSUE TITLE
Advertise offering this repo for adoption

### ISSUE THREAD

**Issue by jlapeyre** [jlapeyre/PDL-Fit-Levmar#5]

**Comment by mohawk2** [comment]
@jlapeyre Want me to take it on? ETJ on PAUSE, and you could transfer the repo to PDLPorters (or to my account and I'll transfer it over).

**Comment by jlapeyre** [comment]
Some time ago, I added someone as a co-maintainer. Was it you? I can't find a record in the issues here of this happening. I don't want to clobber that agreement if possible.
But, modulo this issue, yes if you'd like to take it, that would be great!

**Comment by mohawk2** [comment]
According to https://metacpan.org/dist/PDL-Fit-Levmar/permissions, the only person with any permissions on this distro is you. You gave me GitHub permissions for PDL::IO::Matlab, which is now on CPAN (it wasn't before).

How do you feel about granting me PAUSE permissions on this, and on PDL::DSP::Fir, and even maybe Graphics::Libplot? I'd need GitHub permissions too if they're on GitHub, else I can put them on there starting from the excellent Gitpan.

**Comment by jlapeyre** [comment]
Good. I have given you github access and primary permissions on PAUSE.

**Comment by mohawk2** [comment]
> Good. I have given you github access and primary permissions on PAUSE.

Thank you! Interestingly while this shows that: https://pause.perl.org/pause/authenquery?ACTION=peek_dist_perms, this doesn't (at time of writing): https://metacpan.org/dist/PDL-Fit-Levmar/permissions

I'll update the metadata a bit and fix up the open RT issues, then make a release.

**Comment by jlapeyre** [comment]
Hmm. I see the same thing. Let me know if it does not update.

**Comment by mohawk2** [comment]
It's fine, MetaCPAN is not the source of truth, and PAUSE has it right!

Do you have a repo for Graphics::Libplot?

**Comment by jlapeyre** [comment]
No. I, can't find one.

**Comment by mohawk2** [comment]
> No. I, can't find one.

Gitpan to the rescue! Just been closing (and in one case fixing) all the RT tickets :-)

**Comment by mohawk2** [comment]
I've just uploaded 0.0101 to CPAN. Are you content this repo is now adopted and so this issue can be closed? :-)
